[project]
name = "downdetector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.132.0",
    "python-json-logger>=4.0.0",
    "scrapling[fetchers]>=0.3.14",
    "uvicorn>=0.41.0",
]
